---
- hosts: centos
  remote_user: ansible
  become: yes
  become_method: sudo
  vars:
    lamp_packages:
      - httpd
      - php
      - mariadb-server
      - mariadb

  tasks:
  - name: Install LAMP Software
    yum:
      name: "{{  lamp_packages }}"
      state: latest

  - name: Start and Enable Services
    service:
      name: "{{ item }}"
      state: started
      enabled: yes
    loop:
      - httpd
      - mariadb-server  
