---
- hosts: webserver 
  remote_user: ansible
  become: yes
  become_method: sudo
  vars:
#    lamp_packages:
#      - mariadb-server
#      - mariadb
    sitio: taller
    server: www.taller.com.uy
    hostmaster: admin@taller.com.uy

  roles:
  - role: apache-centos
    when: ansible_facts['os_family'] == "RedHat"
  - role: apache-ubuntu
    when: ansible_facts['os_family'] == "Debian"
  - role: php-centos
    when: ansible_facts['os_family'] == "RedHat"
  - role: php-ubuntu
    when: ansible_facts['os_family'] == "Debian"

  tasks:
  - name: Create virtualhost content directories
    file:
      path: "{{ item }}"
      recurse: yes
      state: directory
      owner: apache
      group: apache
      mode: '0755'
    loop:
      - /var/WWW/{{ sitio }}
      - /var/WWW/{{ sitio }}/html
      - /var/WWW/{{ sitio }}/cgi-bin 

#  - name: Start and Enable Services
#    service:
#      name: "{{ item }}"
#      state: started
#      enabled: yes
#    loop:
#      - mariadb
  
  - name: Create virtualhost configuration Centos
    template:
      src: /templates/{{ sitio }}.j2
      dest: /etc/httpd/vhost.d/{{ sitio }}.conf
      owner: root
      mode: '0644'
    when: ansible_facts['os_family'] == "RedHat"
    notify: Restart httpd 

  - name: Create virtualhost configuration Ubuntu
    template:
      src: /templates/{{ sitio }}.j2
      dest: /etc/apache2/sites-enable/{{ sitio }}.conf
      owner: root
      mode: '0644'  
    when: ansible_facts['os_family'] == "Debian"
    notify: Restart apache2

#  - name: Configure Firewall
#    firewalld:
#      service: "{{ item }}"
#      state: enabled
#      permanent: yes
#      immediate: yes
#    loop:
#      - mysql      
